export const POSTS_BEGIN_REQUEST = "POSTS_BEGIN_REQUEST";
export const POSTS_END_REQUEST = "POSTS_END_REQUEST";
export const POSTS_SUCCESS = "POSTS_SUCCESS";
export const POST_SUCCESS = "POST_SUCCESS";
export const POST_CLEAN = "POST_CLEAN";